### ISSUE TITLE
chemo function needs to be updated for drug efficacy 1 and 2

### ISSUE THREAD

**Issue by amanda-minter** [NTD-Modelling-Consortium/ntd-model-sch#13]
https://github.com/NTD-Modelling-Consortium/ntd-model-sch/blob/05a894401f0a18d06c59beb759ed73a1aeffbe37/sch_simulation/helsim_FUNC_KK.py#L869

**Comment by mattg3004** [comment]
this is in a function which isn't used by the code to run from pickle files
